using namespace System

class Spinner {
  [string]$Name
  [TimeSpan]$Interval
  [bool]$IsUnicode
  [string[]]$Frames

  [int] GetFrameIndex([int]$frameCount) {
    return $frameCount % $this.Frames.Length
  }
}

class SpinnerKnown {
  static [Spinner]$Default = [Spinner]@{ Name = 'Default'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('⣷', '⣯', '⣟', '⡿', '⢿', '⣻', '⣽', '⣾') }
  static [Spinner]$Ascii = [Spinner]@{ Name = 'Ascii'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('-', '\\', '|', '/', '-', '\\', '|', '/') }
  static [Spinner]$Dots = [Spinner]@{ Name = 'Dots'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏') }
  static [Spinner]$Dots2 = [Spinner]@{ Name = 'Dots2'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷') }
  static [Spinner]$Dots3 = [Spinner]@{ Name = 'Dots3'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠋', '⠙', '⠚', '⠞', '⠖', '⠦', '⠴', '⠲', '⠳', '⠓') }
  static [Spinner]$Dots4 = [Spinner]@{ Name = 'Dots4'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠄', '⠆', '⠇', '⠋', '⠙', '⠸', '⠰', '⠠', '⠰', '⠸', '⠙', '⠋', '⠇', '⠆') }
  static [Spinner]$Dots5 = [Spinner]@{ Name = 'Dots5'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠋', '⠙', '⠚', '⠒', '⠂', '⠂', '⠒', '⠲', '⠴', '⠦', '⠖', '⠒', '⠐', '⠐', '⠒', '⠓', '⠋') }
  static [Spinner]$Dots6 = [Spinner]@{ Name = 'Dots6'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠁', '⠉', '⠙', '⠚', '⠒', '⠂', '⠂', '⠒', '⠲', '⠴', '⠤', '⠄', '⠄', '⠤', '⠴', '⠲', '⠒', '⠂', '⠂', '⠒', '⠚', '⠙', '⠉', '⠁') }
  static [Spinner]$Dots7 = [Spinner]@{ Name = 'Dots7'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠈', '⠉', '⠋', '⠓', '⠒', '⠐', '⠐', '⠒', '⠖', '⠦', '⠤', '⠠', '⠠', '⠤', '⠦', '⠖', '⠒', '⠐', '⠐', '⠒', '⠓', '⠋', '⠉', '⠈') }
  static [Spinner]$Dots8 = [Spinner]@{ Name = 'Dots8'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠁', '⠁', '⠉', '⠙', '⠚', '⠒', '⠂', '⠂', '⠒', '⠲', '⠴', '⠤', '⠄', '⠄', '⠤', '⠠', '⠠', '⠤', '⠦', '⠖', '⠒', '⠐', '⠐', '⠒', '⠓', '⠋', '⠉', '⠈', '⠈') }
  static [Spinner]$Dots9 = [Spinner]@{ Name = 'Dots9'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⢹', '⢺', '⢼', '⣸', '⣇', '⡧', '⡗', '⡏') }
  static [Spinner]$Dots10 = [Spinner]@{ Name = 'Dots10'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⢄', '⢂', '⢁', '⡁', '⡈', '⡐', '⡠') }
  static [Spinner]$Dots11 = [Spinner]@{ Name = 'Dots11'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('⠁', '⠂', '⠄', '⡀', '⢀', '⠠', '⠐', '⠈') }
  static [Spinner]$Dots12 = [Spinner]@{ Name = 'Dots12'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⢀⠀', '⡀⠀', '⠄⠀', '⢂⠀', '⡂⠀', '⠅⠀', '⢃⠀', '⡃⠀', '⠍⠀', '⢋⠀', '⡋⠀', '⠍⠁', '⢋⠁', '⡋⠁', '⠍⠉', '⠋⠉', '⠋⠉', '⠉⠙', '⠉⠙', '⠉⠩', '⠈⢙', '⠈⡙', '⢈⠩', '⡀⢙', '⠄⡙', '⢂⠩', '⡂⢘', '⠅⡘', '⢃⠨', '⡃⢐', '⠍⡐', '⢋⠠', '⡋⢀', '⠍⡁', '⢋⠁', '⡋⠁', '⠍⠉', '⠋⠉', '⠋⠉', '⠉⠙', '⠉⠙', '⠉⠩', '⠈⢙', '⠈⡙', '⠈⠩', '⠀⢙', '⠀⡙', '⠀⠩', '⠀⢘', '⠀⡘', '⠀⠨', '⠀⢐', '⠀⡐', '⠀⠠', '⠀⢀', '⠀⡀') }
  static [Spinner]$Dots13 = [Spinner]@{ Name = 'Dots13'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⣼', '⣹', '⢻', '⠿', '⡟', '⣏', '⣧', '⣶') }
  static [Spinner]$Dots14 = [Spinner]@{ Name = 'Dots14'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠉⠉', '⠈⠙', '⠀⠹', '⠀⢸', '⠀⣰', '⢀⣠', '⣀⣀', '⣄⡀', '⣆⠀', '⡇⠀', '⠏⠀', '⠋⠁') }
  static [Spinner]$Dots8Bit = [Spinner]@{ Name = 'Dots8Bit'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠀', '⠁', '⠂', '⠃', '⠄', '⠅', '⠆', '⠇', '⡀', '⡁', '⡂', '⡃', '⡄', '⡅', '⡆', '⡇', '⠈', '⠉', '⠊', '⠋', '⠌', '⠍', '⠎', '⠏', '⡈', '⡉', '⡊', '⡋', '⡌', '⡍', '⡎', '⡏', '⠐', '⠑', '⠒', '⠓', '⠔', '⠕', '⠖', '⠗', '⡐', '⡑', '⡒', '⡓', '⡔', '⡕', '⡖', '⡗', '⠘', '⠙', '⠚', '⠛', '⠜', '⠝', '⠞', '⠟', '⡘', '⡙', '⡚', '⡛', '⡜', '⡝', '⡞', '⡟', '⠠', '⠡', '⠢', '⠣', '⠤', '⠥', '⠦', '⠧', '⡠', '⡡', '⡢', '⡣', '⡤', '⡥', '⡦', '⡧', '⠨', '⠩', '⠪', '⠫', '⠬', '⠭', '⠮', '⠯', '⡨', '⡩', '⡪', '⡫', '⡬', '⡭', '⡮', '⡯', '⠰', '⠱', '⠲', '⠳', '⠴', '⠵', '⠶', '⠷', '⡰', '⡱', '⡲', '⡳', '⡴', '⡵', '⡶', '⡷', '⠸', '⠹', '⠺', '⠻', '⠼', '⠽', '⠾', '⠿', '⡸', '⡹', '⡺', '⡻', '⡼', '⡽', '⡾', '⡿', '⢀', '⢁', '⢂', '⢃', '⢄', '⢅', '⢆', '⢇', '⣀', '⣁', '⣂', '⣃', '⣄', '⣅', '⣆', '⣇', '⢈', '⢉', '⢊', '⢋', '⢌', '⢍', '⢎', '⢏', '⣈', '⣉', '⣊', '⣋', '⣌', '⣍', '⣎', '⣏', '⢐', '⢑', '⢒', '⢓', '⢔', '⢕', '⢖', '⢗', '⣐', '⣑', '⣒', '⣓', '⣔', '⣕', '⣖', '⣗', '⢘', '⢙', '⢚', '⢛', '⢜', '⢝', '⢞', '⢟', '⣘', '⣙', '⣚', '⣛', '⣜', '⣝', '⣞', '⣟', '⢠', '⢡', '⢢', '⢣', '⢤', '⢥', '⢦', '⢧', '⣠', '⣡', '⣢', '⣣', '⣤', '⣥', '⣦', '⣧', '⢨', '⢩', '⢪', '⢫', '⢬', '⢭', '⢮', '⢯', '⣨', '⣩', '⣪', '⣫', '⣬', '⣭', '⣮', '⣯', '⢰', '⢱', '⢲', '⢳', '⢴', '⢵', '⢶', '⢷', '⣰', '⣱', '⣲', '⣳', '⣴', '⣵', '⣶', '⣷', '⢸', '⢹', '⢺', '⢻', '⢼', '⢽', '⢾', '⢿', '⣸', '⣹', '⣺', '⣻', '⣼', '⣽', '⣾', '⣿') }
  static [Spinner]$DotsCircle = [Spinner]@{ Name = 'DotsCircle'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⢎ ', '⠎⠁', '⠊⠑', '⠈⠱', ' ⡱', '⢀⡰', '⢄⡠', '⢆⡀') }
  static [Spinner]$Sand = [Spinner]@{ Name = 'Sand'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⠁', '⠂', '⠄', '⡀', '⡈', '⡐', '⡠', '⣀', '⣁', '⣂', '⣄', '⣌', '⣔', '⣤', '⣥', '⣦', '⣮', '⣶', '⣷', '⣿', '⡿', '⠿', '⢟', '⠟', '⡛', '⠛', '⠫', '⢋', '⠋', '⠍', '⡉', '⠉', '⠑', '⠡', '⢁') }
  static [Spinner]$Line = [Spinner]@{ Name = 'Line'; Interval = [TimeSpan]::FromMilliseconds(130); IsUnicode = $false; Frames = @('-', '\\', '|', '/') }
  static [Spinner]$Line2 = [Spinner]@{ Name = 'Line2'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $false; Frames = @('⠂', '-', '–', '—', '–', '-') }
  static [Spinner]$Pipe = [Spinner]@{ Name = 'Pipe'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $false; Frames = @('┤', '┘', '┴', '└', '├', '┌', '┬', '┐') }
  static [Spinner]$SimpleDots = [Spinner]@{ Name = 'SimpleDots'; Interval = [TimeSpan]::FromMilliseconds(400); IsUnicode = $false; Frames = @('.  ', '.. ', '...', '   ') }
  static [Spinner]$SimpleDotsScrolling = [Spinner]@{ Name = 'SimpleDotsScrolling'; Interval = [TimeSpan]::FromMilliseconds(200); IsUnicode = $false; Frames = @('.  ', '.. ', '...', ' ..', '  .', '   ') }
  static [Spinner]$Star = [Spinner]@{ Name = 'Star'; Interval = [TimeSpan]::FromMilliseconds(70); IsUnicode = $true; Frames = @('✶', '✸', '✹', '✺', '✹', '✷') }
  static [Spinner]$Star2 = [Spinner]@{ Name = 'Star2'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $false; Frames = @('+', 'x', '*') }
  static [Spinner]$Flip = [Spinner]@{ Name = 'Flip'; Interval = [TimeSpan]::FromMilliseconds(70); IsUnicode = $false; Frames = @('_', '_', '_', '-', '`', '`', '''', '´', '-', '_', '_', '_') }
  static [Spinner]$Hamburger = [Spinner]@{ Name = 'Hamburger'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('☱', '☲', '☴') }
  static [Spinner]$GrowVertical = [Spinner]@{ Name = 'GrowVertical'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('▁', '▃', '▄', '▅', '▆', '▇', '▆', '▅', '▄', '▃') }
  static [Spinner]$GrowHorizontal = [Spinner]@{ Name = 'GrowHorizontal'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('▏', '▎', '▍', '▌', '▋', '▊', '▉', '▊', '▋', '▌', '▍', '▎') }
  static [Spinner]$Balloon = [Spinner]@{ Name = 'Balloon'; Interval = [TimeSpan]::FromMilliseconds(140); IsUnicode = $false; Frames = @(' ', '.', 'o', 'O', '@', '*', ' ') }
  static [Spinner]$Balloon2 = [Spinner]@{ Name = 'Balloon2'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $false; Frames = @('.', 'o', 'O', '°', 'O', 'o', '.') }
  static [Spinner]$Noise = [Spinner]@{ Name = 'Noise'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('▓', '▒', '░') }
  static [Spinner]$Bounce = [Spinner]@{ Name = 'Bounce'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('⠁', '⠂', '⠄', '⠂') }
  static [Spinner]$BoxBounce = [Spinner]@{ Name = 'BoxBounce'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('▖', '▘', '▝', '▗') }
  static [Spinner]$BoxBounce2 = [Spinner]@{ Name = 'BoxBounce2'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('▌', '▀', '▐', '▄') }
  static [Spinner]$Triangle = [Spinner]@{ Name = 'Triangle'; Interval = [TimeSpan]::FromMilliseconds(50); IsUnicode = $true; Frames = @('◢', '◣', '◤', '◥') }
  static [Spinner]$Binary = [Spinner]@{ Name = 'Binary'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $false; Frames = @('010010', '001100', '100101', '111010', '111101', '010111', '101011', '111000', '110011', '110101') }
  static [Spinner]$Arc = [Spinner]@{ Name = 'Arc'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('◜', '◠', '◝', '◞', '◡', '◟') }
  static [Spinner]$Circle = [Spinner]@{ Name = 'Circle'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('◡', '⊙', '◠') }
  static [Spinner]$SquareCorners = [Spinner]@{ Name = 'SquareCorners'; Interval = [TimeSpan]::FromMilliseconds(180); IsUnicode = $true; Frames = @('◰', '◳', '◲', '◱') }
  static [Spinner]$CircleQuarters = [Spinner]@{ Name = 'CircleQuarters'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('◴', '◷', '◶', '◵') }
  static [Spinner]$CircleHalves = [Spinner]@{ Name = 'CircleHalves'; Interval = [TimeSpan]::FromMilliseconds(50); IsUnicode = $true; Frames = @('◐', '◓', '◑', '◒') }
  static [Spinner]$Squish = [Spinner]@{ Name = 'Squish'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('╫', '╪') }
  static [Spinner]$Toggle = [Spinner]@{ Name = 'Toggle'; Interval = [TimeSpan]::FromMilliseconds(250); IsUnicode = $true; Frames = @('⊶', '⊷') }
  static [Spinner]$Toggle2 = [Spinner]@{ Name = 'Toggle2'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('▫', '▪') }
  static [Spinner]$Toggle3 = [Spinner]@{ Name = 'Toggle3'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('□', '■') }
  static [Spinner]$Toggle4 = [Spinner]@{ Name = 'Toggle4'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('■', '□', '▪', '▫') }
  static [Spinner]$Toggle5 = [Spinner]@{ Name = 'Toggle5'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('▮', '▯') }
  static [Spinner]$Toggle6 = [Spinner]@{ Name = 'Toggle6'; Interval = [TimeSpan]::FromMilliseconds(300); IsUnicode = $true; Frames = @('ဝ', '၀') }
  static [Spinner]$Toggle7 = [Spinner]@{ Name = 'Toggle7'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⦾', '⦿') }
  static [Spinner]$Toggle8 = [Spinner]@{ Name = 'Toggle8'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('◍', '◌') }
  static [Spinner]$Toggle9 = [Spinner]@{ Name = 'Toggle9'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('◉', '◎') }
  static [Spinner]$Toggle10 = [Spinner]@{ Name = 'Toggle10'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('㊂', '㊀', '㊁') }
  static [Spinner]$Toggle11 = [Spinner]@{ Name = 'Toggle11'; Interval = [TimeSpan]::FromMilliseconds(50); IsUnicode = $true; Frames = @('⧇', '⧆') }
  static [Spinner]$Toggle12 = [Spinner]@{ Name = 'Toggle12'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('☗', '☖') }
  static [Spinner]$Toggle13 = [Spinner]@{ Name = 'Toggle13'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $false; Frames = @('=', '*', '-') }
  static [Spinner]$Arrow = [Spinner]@{ Name = 'Arrow'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('←', '↖', '↑', '↗', '→', '↘', '↓', '↙') }
  static [Spinner]$Arrow2 = [Spinner]@{ Name = 'Arrow2'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('⬆️ ', '↗️ ', '➡️ ', '↘️ ', '⬇️ ', '↙️ ', '⬅️ ', '↖️ ') }
  static [Spinner]$Arrow3 = [Spinner]@{ Name = 'Arrow3'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('▹▹▹▹▹', '▸▹▹▹▹', '▹▸▹▹▹', '▹▹▸▹▹', '▹▹▹▸▹', '▹▹▹▹▸') }
  static [Spinner]$BouncingBar = [Spinner]@{ Name = 'BouncingBar'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('[    ]', '[=   ]', '[==  ]', '[=== ]', '[====]', '[ ===]', '[  ==]', '[   =]', '[    ]', '[   =]', '[  ==]', '[ ===]', '[====]', '[=== ]', '[==  ]', '[=   ]') }
  static [Spinner]$BouncingBall = [Spinner]@{ Name = 'BouncingBall'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('( ●    )', '(  ●   )', '(   ●  )', '(    ● )', '(     ●)', '(    ● )', '(   ●  )', '(  ●   )', '( ●    )', '(●     )') }
  static [Spinner]$Smiley = [Spinner]@{ Name = 'Smiley'; Interval = [TimeSpan]::FromMilliseconds(200); IsUnicode = $true; Frames = @('😄 ', '😝 ') }
  static [Spinner]$Monkey = [Spinner]@{ Name = 'Monkey'; Interval = [TimeSpan]::FromMilliseconds(300); IsUnicode = $true; Frames = @('🙈 ', '🙈 ', '🙉 ', '🙊 ') }
  static [Spinner]$Hearts = [Spinner]@{ Name = 'Hearts'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('💛 ', '💙 ', '💜 ', '💚 ', '❤️ ') }
  static [Spinner]$Clock = [Spinner]@{ Name = 'Clock'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('🕛 ', '🕐 ', '🕑 ', '🕒 ', '🕓 ', '🕔 ', '🕕 ', '🕖 ', '🕗 ', '🕘 ', '🕙 ', '🕚 ') }
  static [Spinner]$Earth = [Spinner]@{ Name = 'Earth'; Interval = [TimeSpan]::FromMilliseconds(180); IsUnicode = $true; Frames = @('🌍 ', '🌎 ', '🌏 ') }
  static [Spinner]$Material = [Spinner]@{ Name = 'Material'; Interval = [TimeSpan]::FromMilliseconds(17); IsUnicode = $true; Frames = @('█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '███▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '████▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '██████▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '███████▁▁▁▁▁▁▁▁▁▁▁▁▁', '████████▁▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '██████████▁▁▁▁▁▁▁▁▁▁', '███████████▁▁▁▁▁▁▁▁▁', '█████████████▁▁▁▁▁▁▁', '██████████████▁▁▁▁▁▁', '██████████████▁▁▁▁▁▁', '▁██████████████▁▁▁▁▁', '▁██████████████▁▁▁▁▁', '▁██████████████▁▁▁▁▁', '▁▁██████████████▁▁▁▁', '▁▁▁██████████████▁▁▁', '▁▁▁▁█████████████▁▁▁', '▁▁▁▁██████████████▁▁', '▁▁▁▁██████████████▁▁', '▁▁▁▁▁██████████████▁', '▁▁▁▁▁██████████████▁', '▁▁▁▁▁██████████████▁', '▁▁▁▁▁▁██████████████', '▁▁▁▁▁▁██████████████', '▁▁▁▁▁▁▁█████████████', '▁▁▁▁▁▁▁█████████████', '▁▁▁▁▁▁▁▁████████████', '▁▁▁▁▁▁▁▁████████████', '▁▁▁▁▁▁▁▁▁███████████', '▁▁▁▁▁▁▁▁▁███████████', '▁▁▁▁▁▁▁▁▁▁██████████', '▁▁▁▁▁▁▁▁▁▁██████████', '▁▁▁▁▁▁▁▁▁▁▁▁████████', '▁▁▁▁▁▁▁▁▁▁▁▁▁███████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁██████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████', '█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████', '██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███', '██▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███', '███▁▁▁▁▁▁▁▁▁▁▁▁▁▁███', '████▁▁▁▁▁▁▁▁▁▁▁▁▁▁██', '█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█', '█████▁▁▁▁▁▁▁▁▁▁▁▁▁▁█', '██████▁▁▁▁▁▁▁▁▁▁▁▁▁█', '████████▁▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '█████████▁▁▁▁▁▁▁▁▁▁▁', '███████████▁▁▁▁▁▁▁▁▁', '████████████▁▁▁▁▁▁▁▁', '████████████▁▁▁▁▁▁▁▁', '██████████████▁▁▁▁▁▁', '██████████████▁▁▁▁▁▁', '▁██████████████▁▁▁▁▁', '▁██████████████▁▁▁▁▁', '▁▁▁█████████████▁▁▁▁', '▁▁▁▁▁████████████▁▁▁', '▁▁▁▁▁████████████▁▁▁', '▁▁▁▁▁▁███████████▁▁▁', '▁▁▁▁▁▁▁▁█████████▁▁▁', '▁▁▁▁▁▁▁▁█████████▁▁▁', '▁▁▁▁▁▁▁▁▁█████████▁▁', '▁▁▁▁▁▁▁▁▁█████████▁▁', '▁▁▁▁▁▁▁▁▁▁█████████▁', '▁▁▁▁▁▁▁▁▁▁▁████████▁', '▁▁▁▁▁▁▁▁▁▁▁████████▁', '▁▁▁▁▁▁▁▁▁▁▁▁███████▁', '▁▁▁▁▁▁▁▁▁▁▁▁███████▁', '▁▁▁▁▁▁▁▁▁▁▁▁▁███████', '▁▁▁▁▁▁▁▁▁▁▁▁▁███████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁████', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁███', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁██', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁', '▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁') }
  static [Spinner]$Moon = [Spinner]@{ Name = 'Moon'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('🌑 ', '🌒 ', '🌓 ', '🌔 ', '🌕 ', '🌖 ', '🌗 ', '🌘 ') }
  static [Spinner]$Runner = [Spinner]@{ Name = 'Runner'; Interval = [TimeSpan]::FromMilliseconds(140); IsUnicode = $true; Frames = @('🚶 ', '🏃 ') }
  static [Spinner]$Pong = [Spinner]@{ Name = 'Pong'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('▐⠂       ▌', '▐⠈       ▌', '▐ ⠂      ▌', '▐ ⠠      ▌', '▐  ⡀     ▌', '▐  ⠠     ▌', '▐   ⠂    ▌', '▐   ⠈    ▌', '▐    ⠂   ▌', '▐    ⠠   ▌', '▐     ⡀  ▌', '▐     ⠠  ▌', '▐      ⠂ ▌', '▐      ⠈ ▌', '▐       ⠂▌', '▐       ⠠▌', '▐       ⡀▌', '▐      ⠠ ▌', '▐      ⠂ ▌', '▐     ⠈  ▌', '▐     ⠂  ▌', '▐    ⠠   ▌', '▐    ⡀   ▌', '▐   ⠠    ▌', '▐   ⠂    ▌', '▐  ⠈     ▌', '▐  ⠂     ▌', '▐ ⠠      ▌', '▐ ⡀      ▌', '▐⠠       ▌') }
  static [Spinner]$Shark = [Spinner]@{ Name = 'Shark'; Interval = [TimeSpan]::FromMilliseconds(120); IsUnicode = $true; Frames = @('▐|\\____________▌', '▐_|\\___________▌', '▐__|\\__________▌', '▐___|\\_________▌', '▐____|\\________▌', '▐_____|\\_______▌', '▐______|\\______▌', '▐_______|\\_____▌', '▐________|\\____▌', '▐_________|\\___▌', '▐__________|\\__▌', '▐___________|\\_▌', '▐____________|\\▌', '▐____________/|▌', '▐___________/|_▌', '▐__________/|__▌', '▐_________/|___▌', '▐________/|____▌', '▐_______/|_____▌', '▐______/|______▌', '▐_____/|_______▌', '▐____/|________▌', '▐___/|_________▌', '▐__/|__________▌', '▐_/|___________▌', '▐/|____________▌') }
  static [Spinner]$Dqpb = [Spinner]@{ Name = 'Dqpb'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $false; Frames = @('d', 'q', 'p', 'b') }
  static [Spinner]$Weather = [Spinner]@{ Name = 'Weather'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('☀️ ', '☀️ ', '☀️ ', '🌤 ', '⛅️ ', '🌥 ', '☁️ ', '🌧 ', '🌨 ', '🌧 ', '🌨 ', '🌧 ', '🌨 ', '⛈ ', '🌨 ', '🌧 ', '🌨 ', '☁️ ', '🌥 ', '⛅️ ', '🌤 ', '☀️ ', '☀️ ') }
  static [Spinner]$Christmas = [Spinner]@{ Name = 'Christmas'; Interval = [TimeSpan]::FromMilliseconds(400); IsUnicode = $true; Frames = @('🌲', '🎄') }
  static [Spinner]$Grenade = [Spinner]@{ Name = 'Grenade'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('،  ', '′  ', ' ´ ', ' ‾ ', '  ⸌', '  ⸊', '  |', '  ⁎', '  ⁕', ' ෴ ', '  ⁓', '   ', '   ', '   ') }
  static [Spinner]$Point = [Spinner]@{ Name = 'Point'; Interval = [TimeSpan]::FromMilliseconds(125); IsUnicode = $true; Frames = @('∙∙∙', '●∙∙', '∙●∙', '∙∙●', '∙∙∙') }
  static [Spinner]$Layer = [Spinner]@{ Name = 'Layer'; Interval = [TimeSpan]::FromMilliseconds(150); IsUnicode = $true; Frames = @('-', '=', '≡') }
  static [Spinner]$BetaWave = [Spinner]@{ Name = 'BetaWave'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('ρββββββ', 'βρβββββ', 'ββρββββ', 'βββρβββ', 'ββββρββ', 'βββββρβ', 'ββββββρ') }
  static [Spinner]$FingerDance = [Spinner]@{ Name = 'FingerDance'; Interval = [TimeSpan]::FromMilliseconds(160); IsUnicode = $true; Frames = @('🤘 ', '🤟 ', '🖖 ', '✋ ', '🤚 ', '👆 ') }
  static [Spinner]$FistBump = [Spinner]@{ Name = 'FistBump'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('🤜　　　　🤛 ', '🤜　　　　🤛 ', '🤜　　　　🤛 ', '　🤜　　🤛　 ', '　　🤜🤛　　 ', '　🤜✨🤛　　 ', '🤜　✨　🤛　 ') }
  static [Spinner]$SoccerHeader = [Spinner]@{ Name = 'SoccerHeader'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @(' 🧑⚽️       🧑 ', '🧑  ⚽️      🧑 ', '🧑   ⚽️     🧑 ', '🧑    ⚽️    🧑 ', '🧑     ⚽️   🧑 ', '🧑      ⚽️  🧑 ', '🧑       ⚽️🧑  ', '🧑      ⚽️  🧑 ', '🧑     ⚽️   🧑 ', '🧑    ⚽️    🧑 ', '🧑   ⚽️     🧑 ', '🧑  ⚽️      🧑 ') }
  static [Spinner]$Mindblown = [Spinner]@{ Name = 'Mindblown'; Interval = [TimeSpan]::FromMilliseconds(160); IsUnicode = $true; Frames = @('😐 ', '😐 ', '😮 ', '😮 ', '😦 ', '😦 ', '😧 ', '😧 ', '🤯 ', '💥 ', '✨ ', '　 ', '　 ', '　 ') }
  static [Spinner]$Speaker = [Spinner]@{ Name = 'Speaker'; Interval = [TimeSpan]::FromMilliseconds(160); IsUnicode = $true; Frames = @('🔈 ', '🔉 ', '🔊 ', '🔉 ') }
  static [Spinner]$OrangePulse = [Spinner]@{ Name = 'OrangePulse'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('🔸 ', '🔶 ', '🟠 ', '🟠 ', '🔶 ') }
  static [Spinner]$BluePulse = [Spinner]@{ Name = 'BluePulse'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('🔹 ', '🔷 ', '🔵 ', '🔵 ', '🔷 ') }
  static [Spinner]$OrangeBluePulse = [Spinner]@{ Name = 'OrangeBluePulse'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('🔸 ', '🔶 ', '🟠 ', '🟠 ', '🔶 ', '🔹 ', '🔷 ', '🔵 ', '🔵 ', '🔷 ') }
  static [Spinner]$TimeTravel = [Spinner]@{ Name = 'TimeTravel'; Interval = [TimeSpan]::FromMilliseconds(100); IsUnicode = $true; Frames = @('🕛 ', '🕚 ', '🕙 ', '🕘 ', '🕗 ', '🕖 ', '🕕 ', '🕔 ', '🕓 ', '🕒 ', '🕑 ', '🕐 ') }
  static [Spinner]$Aesthetic = [Spinner]@{ Name = 'Aesthetic'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @('▰▱▱▱▱▱▱', '▰▰▱▱▱▱▱', '▰▰▰▱▱▱▱', '▰▰▰▰▱▱▱', '▰▰▰▰▰▱▱', '▰▰▰▰▰▰▱', '▰▰▰▰▰▰▰', '▰▱▱▱▱▱▱') }
  static [Spinner]$DwarfFortress = [Spinner]@{ Name = 'DwarfFortress'; Interval = [TimeSpan]::FromMilliseconds(80); IsUnicode = $true; Frames = @(' ██████£££  ', '☺██████£££  ', '☺██████£££  ', '☺▓█████£££  ', '☺▓█████£££  ', '☺▒█████£££  ', '☺▒█████£££  ', '☺░█████£££  ', '☺░█████£££  ', '☺ █████£££  ', ' ☺█████£££  ', ' ☺█████£££  ', ' ☺▓████£££  ', ' ☺▓████£££  ', ' ☺▒████£££  ', ' ☺▒████£££  ', ' ☺░████£££  ', ' ☺░████£££  ', ' ☺ ████£££  ', '  ☺████£££  ', '  ☺████£££  ', '  ☺▓███£££  ', '  ☺▓███£££  ', '  ☺▒███£££  ', '  ☺▒███£££  ', '  ☺░███£££  ', '  ☺░███£££  ', '  ☺ ███£££  ', '   ☺███£££  ', '   ☺███£££  ', '   ☺▓██£££  ', '   ☺▓██£££  ', '   ☺▒██£££  ', '   ☺▒██£££  ', '   ☺░██£££  ', '   ☺░██£££  ', '   ☺ ██£££  ', '    ☺██£££  ', '    ☺██£££  ', '    ☺▓█£££  ', '    ☺▓█£££  ', '    ☺▒█£££  ', '    ☺▒█£££  ', '    ☺░█£££  ', '    ☺░█£££  ', '    ☺ █£££  ', '     ☺█£££  ', '     ☺█£££  ', '     ☺▓£££  ', '     ☺▓£££  ', '     ☺▒£££  ', '     ☺▒£££  ', '     ☺░£££  ', '     ☺░£££  ', '     ☺ £££  ', '      ☺£££  ', '      ☺£££  ', '      ☺▓££  ', '      ☺▓££  ', '      ☺▒££  ', '      ☺▒££  ', '      ☺░££  ', '      ☺░££  ', '      ☺ ££  ', '       ☺££  ', '       ☺££  ', '       ☺▓£  ', '       ☺▓£  ', '       ☺▒£  ', '       ☺▒£  ', '       ☺░£  ', '       ☺░£  ', '       ☺ £  ', '        ☺£  ', '        ☺£  ', '        ☺▓  ', '        ☺▓  ', '        ☺▒  ', '        ☺▒  ', '        ☺░  ', '        ☺░  ', '        ☺   ', '        ☺  &', '        ☺ ☼&', '       ☺ ☼ &', '       ☺☼  &', '      ☺☼  & ', '      ‼   & ', '     ☺   &  ', '    ‼    &  ', '   ☺    &   ', '  ‼     &   ', ' ☺     &    ', '‼      &    ', '      &     ', '      &     ', '     &   ░  ', '     &   ▒  ', '    &    ▓  ', '    &    £  ', '   &    ░£  ', '   &    ▒£  ', '  &     ▓£  ', '  &     ££  ', ' &     ░££  ', ' &     ▒££  ', '&      ▓££  ', '&      £££  ', '      ░£££  ', '      ▒£££  ', '      ▓£££  ', '      █£££  ', '     ░█£££  ', '     ▒█£££  ', '     ▓█£££  ', '     ██£££  ', '    ░██£££  ', '    ▒██£££  ', '    ▓██£££  ', '    ███£££  ', '   ░███£££  ', '   ▒███£££  ', '   ▓███£££  ', '   ████£££  ', '  ░████£££  ', '  ▒████£££  ', '  ▓████£££  ', '  █████£££  ', ' ░█████£££  ', ' ▒█████£££  ', ' ▓█████£££  ', ' ██████£££  ', ' ██████£££  ') }
}

